async def t(pg, B):
    E = pg.evaluate
    await pg.goto(B + "/", wait_until="load"); await pg.wait_for_timeout(3000)
    await E("scrollTo(0, document.querySelector('#moments').offsetTop + 900)"); await pg.wait_for_timeout(2500)
    box = await E("(()=>{const cs=[...document.querySelectorAll('.holo')]; const c=cs.find(c=>{const r=c.getBoundingClientRect(); return r.left>300&&r.right<1400}); const r=c.getBoundingClientRect(); return [r.left,r.top,r.width,r.height,cs.indexOf(c)]})()")
    await pg.mouse.move(box[0] + box[2] * .5, box[1] + box[3] * .5); await pg.wait_for_timeout(200)
    await pg.mouse.move(box[0] + box[2] * .95, box[1] + box[3] * .1); await pg.wait_for_timeout(600)
    print("A holo", box[4], "--ry", await E(f"document.querySelectorAll('.holo')[{box[4]}].style.getPropertyValue('--ry')"), "| inline transform:", await E(f"document.querySelectorAll('.holo')[{box[4]}].style.transform"))
    print("C chain06 label bottom vs map bottom", await E("(()=>{document.querySelector('.chain-map').scrollIntoView(); return [document.querySelectorAll('.chain-node .label')[5].getBoundingClientRect().bottom, document.querySelector('.chain-map').getBoundingClientRect().bottom]})()"))
    await pg.goto(B + "/lab/#quiz", wait_until="load"); await pg.wait_for_timeout(2000)
    a1 = await E("[document.querySelector('#quiz-quote').textContent, document.querySelector('#quiz-quote').getAttribute('aria-label')]")
    await E("document.querySelector('#quiz-options button').click()"); await E("document.querySelector('#quiz-next').click()"); await pg.wait_for_timeout(300)
    a2 = await E("[document.querySelector('#quiz-quote').textContent, document.querySelector('#quiz-quote').getAttribute('aria-label'), document.querySelectorAll('#quiz-quote .split-char').length]")
    print("D quiz Q1", a1, "| Q2", a2)
    await pg.goto(B + "/lab/#reel", wait_until="load"); await pg.wait_for_timeout(2000)
    await E("document.querySelector('#reel-deck').scrollIntoView({block:'center'})"); await pg.wait_for_timeout(500)
    b = await E("(()=>{const r=document.querySelector('#reel-deck').getBoundingClientRect(); return [r.left,r.top,r.width,r.height]})()")
    await pg.mouse.move(b[0] + b[2] * .8, b[1] + b[3] * .5); await pg.mouse.down(); await pg.mouse.move(b[0] + b[2] * .2, b[1] + b[3] * .5, steps=8); await pg.mouse.up()
    await pg.wait_for_timeout(1500)
    print("E after mouse swipe on reel, path:", await E("location.pathname"))
    print("F reel card aria-label after swipe", await E("document.querySelector('.reel-card:last-child .q').getAttribute('aria-label')"))
