async def t(pg, B):
    E = pg.evaluate
    await pg.goto(B + "/moments/niisan-akan/", wait_until="load"); await pg.wait_for_timeout(3000)
    print("A ghost pos vs aside", await E("[document.querySelector('.d-ghost').getBoundingClientRect().toJSON(), document.querySelector('.d-aside').getBoundingClientRect().top]"))
    print("B dots at load", await E("[...document.querySelectorAll('.d-beat-dots i')].map(i=>i.className)"))
    await E("scrollTo(0, document.querySelector('#story').offsetTop + innerHeight*2.2)"); await pg.wait_for_timeout(1500)
    print("C beats active", await E("[...document.querySelectorAll('.beat')].map(b=>b.classList.contains('is-active'))"), "dots", await E("[...document.querySelectorAll('.d-beat-dots i')].map(i=>i.className)"))
    await E("scrollTo(0, 0)"); await pg.wait_for_timeout(1500)
    print("D back to top beats active", await E("[...document.querySelectorAll('.beat')].map(b=>b.classList.contains('is-active'))"), "dots", await E("[...document.querySelectorAll('.d-beat-dots i')].map(i=>i.className)"))
    await E("scrollTo(0, document.body.scrollHeight)"); await pg.wait_for_timeout(1500)
    print("E beats after passing all", await E("[...document.querySelectorAll('.beat')].map(b=>b.classList.contains('is-active'))"))
    print("F insight inline transform", await E("document.querySelector('.insight').style.transform"))
    await pg.goto(B + "/404.html", wait_until="load"); await pg.wait_for_timeout(2000)
    print("G 404 footer?", await E("!!document.querySelector('.site-footer')"), "h1 aria", await E("document.querySelector('.nf-code').getAttribute('aria-label')"))
    await pg.screenshot(path="/tmp/nf.png")
    await pg.goto(B + "/credits/", wait_until="load"); await pg.wait_for_timeout(2000)
    await pg.screenshot(path="/tmp/credits.png", full_page=True)
    print("H credits nav current", await E("[...document.querySelectorAll('.header-nav [aria-current]')].map(a=>a.textContent)"))
    await pg.goto(B + "/moments/niisan-akan/", wait_until="load"); await pg.wait_for_timeout(1500)
    print("I detail nav current", await E("[...document.querySelectorAll('.header-nav [aria-current]')].map(a=>a.textContent)"))
